//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoLabs.Web.Templates {
    
    
    public partial class BareboneDetail {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new UmbracoLabs.Web.Templates.Barebone Master {
            get {
                return ((UmbracoLabs.Web.Templates.Barebone)(base.Master));
            }
        }
    }
}
